ARG VERSION
FROM almalinux:${VERSION:-9}
ARG course="Devops" \
    Trainer="sivakumar" \
    Joinee="Naresh" \
    Duration="10HRS"
RUN echo "NewJoinee" ${"Joinee"}, trainer: ${"Trainer"}
CMD ["sleep", "1000"]